server:
  error:
    include-stacktrace: on-param
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: rockblin0123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoint:
    web:
      exposure:
        include: "*"

info:
  app: Spring Bott Essentials By DevDojo
